name: Deploy Lambda function
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
            cd functions
            pip install flake8
      - name: Lint With Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python on the runner
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          cd functions
          python -m pip install --upgrade pip
          if [-f requirements.txt]; then pip install -r requirements.txt -t .; fi
      - name : Zip the function
        run: |
          cd functions
          zip -r ../${{ github.sha }}.zip .
      - name: Archive the artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: zipped-bundle
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to S3
        run: aws s3 cp ${{ github.sha }}.zip s3://mysuperbucketfortestingpurpose1/${{ github.sha }}.zip
  test:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create test function
        run: |
          aws lambda create-function --function-name test-function --code S3Bucket=mysuperbucketfortestingpurpose1,S3Key=${{ github.sha }}.zip --handler lambda_function.lambda_handler --runtime python3.11 --role arn:aws:iam::407125164605:role/my-lambda-role
      - name: Wait 30 seconds
        run: sleep 30
      - name: Destroy test function
        if: ${{ always() }}
        run: aws lambda delete-function --function-name test-function
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
    - name: Upload function code to lambda
      run: |
        aws lambda update-function-code \
        --function-name my-functions \
        --s3-bucket mysuperbucketfortestingpurpose1 \
        --s3-key ${{ github.sha }}.zip \
        --publish